# Generated by Django 6.0.3 on 2026-03-23 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelacademy", "0002_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacao",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos_cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="orcamento",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="prazo",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="freelancer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propostas_enviadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="mensagem",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="prazo_estimado",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aceite", "Aceite"),
                    ("recusado", "Recusado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="valor_cobrado",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf_cnpj",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="perfil_publico",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
