# Generated by Django 6.0.3 on 2026-03-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelacademy", "0003_notificacao_link_alter_projeto_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="saldo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
