# Generated by Django 6.0.2 on 2026-02-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_avaliacao', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=255)),
                ('data_avaliacao', models.DateField()),
                ('id_freelancer', models.IntegerField()),
                ('id_empresa', models.IntegerField()),
                ('id_projeto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.IntegerField()),
                ('data_assinatura', models.DateField()),
                ('valor_acordado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_contrato', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('id_proposta', models.IntegerField()),
                ('id_freelancer', models.IntegerField()),
                ('id_empresa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_freelancer', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('foto_perfil', models.TextField()),
                ('data_cadastro', models.DateField()),
                ('avaliacao_media', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagamento', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('metodo_pagamento', models.BooleanField(default=True)),
                ('status_pagamento', models.BooleanField(default=True)),
                ('id_contrato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projeto', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status_projeto', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empresa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proposta', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('status_proposta', models.BooleanField(default=True)),
                ('id_freelancer', models.IntegerField()),
                ('id_projeto', models.IntegerField()),
            ],
        ),
    ]
