# Generated by Django 6.0.2 on 2026-03-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelacademy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
