# Generated by Django 6.0.2 on 2026-03-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelacademy_app', '0002_freelancer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='password',
        ),
    ]
